hangdict = {
    "countries": ["Countries",
        ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
         "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium",
         "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
         "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad",
         "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
         "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador",
         "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia",
         "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea Bissau", "Guyana", "Haiti",
         "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
         "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "North Korea", "South Korea",
         "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
         "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
         "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
         "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand",
         "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama",
         "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia",
         "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
         "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
         "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka",
         "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania",
         "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
         "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
         "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe", "Democratic Republic of the Congo",
         "Scotland", "England", "Wales"]],
    "cities": ["Cities",
        ["Chongqing", "Shanghai", "Delhi", "Beijing", "Mumbai", "Lagos", "Karachi", "Dhaka", "Guangzhou", "Istanbul",
         "Tokyo", "Bengaluru", "Moscow", "Sao Paulo", "Lahore", "Cairo", "Kinshasa", "Jakarta", "Seoul", "Wenzhou",
         "Mexico City", "Lima", "London", "Xian", "Hyderabad", "New York City", "Chennai", "Shenzhen", "Bangkok",
         "Suzhou", "Nanjing", "Dongguan", "Tehran", "Quanzhou", "Shenyang", "Bogota", "Ho Chi Minh City", "Hong Kong",
         "Baghdad", "Fuzhou", "Changsha", "Wuhan", "Tianjin", "Hanoi", "Rio de Janeiro", "Qingdao", "Foshan", "Zunyi",
         "Santiago", "Riyadh", "Ahmedabad", "Singapore", "Shantou", "Ankara", "Yangon", "Saint Petersburg",
         "Casablanca", "Abidjan", "Chengdu", "Alexandria", "Kolkata", "Surat", "Johannesburg", "Dar es Salaam",
         "Shijiazhuang", "Harbin", "Giza", "Izmir", "Zhengzhou", "Taipei", "Los Angeles", "Changchun", "Cape Town",
         "Yokohama", "Khartoum", "Guayaquil", "Hangzhou", "Xiamen", "Berlin", "Busan", "Ningbo", "Jeddah", "Durban",
         "Algiers", "Kabul", "Hefei", "Mashhad", "Pyongyang", "Madrid", "Faisalabad", "Baku", "Tangshan", "Ekurhuleni",
         "Nairobi", "Zhongshan", "Pune", "Addis Ababa", "Jaipur", "Buenos Aires", "Incheon", "Quezon City", "Kiev",
         "Salvador", "Rome", "Dubai", "Luanda", "Lucknow", "Kaohsiung", "Kanpur", "Surabaya", "Taichung", "Basra",
         "Toronto", "Chicago", "Osaka", "Quito", "Chaozhou", "Fortaleza", "Chittagong", "Bandung", "Managua",
         "Brasilia", "Belo Horizonte", "Daegu", "Houston", "Douala", "Medellin", "Yaounde", "Nagpur", "Cali",
         "Tashkent", "Nagoya", "Isfahan", "Phnom Penh", "Kochi", "Paris", "Ouagadougou", "Lanzhou", "Kano", "Dalian",
         "Guatemala City", "Havana", "Rawalpindi", "Medan", "Accra", "Visakhapatnam", "Gujranwala", "Jinan", "Minsk",
         "Caracas", "Sanaa", "Bucharest", "Vienna"]],
    "european-cities": ["European Cities",
        ["Moscow", "Istanbul", "Paris", "London", "Madrid", "Barcelona", "Saint Petersburg", "Berlin", "Rome", "Athens",
         "Milan", "Lisbon", "Kiev", "Birmingham", "Naples", "Manchester", "Bucharest", "Brussels", "Minsk", "Belgrade",
         "Hamburg", "Warsaw", "Budapest", "Vienna", "Turin", "Marseille", "Lyon", "Kharkiv", "Porto", "Munich",
         "Stockholm", "Dublin", "Nizhniy Novgorod", "Sofia", "Copenhagen", "Glasgow", "Prague", "Zurich", "Kazan",
         "Samara", "Helsinki", "Amsterdam", "Rostov on Don", "Lille", "Ufa", "Rotterdam", "Odessa", "Dnipropetrovsk",
         "Cologne", "Bonn", "Perm", "Volgograd", "Donetsk", "Antwerp", "Nice", "Newcastle upon Tyne", "Oslo",
         "Thessaloniki", "Saratov", "Liverpool", "Valencia", "Krakow", "The Hague", "Stuttgart", "Sevilla", "Nuremburg",
         "Genoa", "Venice", "Valladolid", "Nantes", "Aarhus", "Tallinn", "Vilnius", "Riga", "Gdansk", "Lubeck",
         "Bern", "Naples", "Valencia", "Ljubljana", "Zagreb", "Sevastopol", "Toledo", "Salzburg", "Lvov", "Tbilisi",
         "Baku", "Yerevan", "Bratislava", "Palermo", "Florence", "Lublin", "Sarajevo", "Tirane", "Toulouse", "Zaragoza",
         "Edinburgh", "Hanover", "Brunswick", "Leipzig", "Dresden", "Skopje"]],
    "american-cities": ["American Cities",
        ["New York City", "Philadelphia", "Chicago", "Houston", "Dallas", "Fort Worth", "San Antonio", "Buffalo",
         "Rochester", "Boston", "Providence", "Hartford", "Augusta", "Portland", "Montpelier", "Manchester", "Concord",
         "New Haven", "Albany", "Troy", "Newark", "Trenton", "Pittsburgh", "Hershey", "Harrisburg",
         "Erie", "Cleveland", "Cincinnati", "Akron", "Columbus", "Indianapolis", "Springfield", "Peoria", "Detroit",
         "Lansing", "Sault Ste Marie", "Madison", "Green Bay", "Milwaukee", "Saint Paul", "Minneapolis", "Billings",
         "Boise", "Denver", "Boulder", "Colorado Springs", "Cheyenne", "Lincoln", "Kansas City", "Saint Louis",
         "Little Rock", "Nashville", "Memphis", "Chattanooga", "Charlotte", "Raleigh", "Durham",
         "Richmond", "Norfolk", "Newport News", "Virginia Beach",  # removed some less relevant NC cities
         "Alexandria", "Washington", "Annapolis", "Baltimore", "Dover", "Jersey City", "Columbia", "Myrtle Beach",
         "Atlanta", "Savannah", "Florence", "Jacksonville", "Miami", "Orlando", "Tallahassee", "Tampa",
         "Fort Lauderdale", "Mobile", "Montgomery", "Baton Rouge", "Jackson", "New Orleans", "Galveston", "El Paso",
         "Oklahoma City", "Tulsa", "Topeka", "Des Moines", "Fargo", "Sioux Falls", "Pierre", "Bismarck",
         "Salt Lake City", "Cambridge", "Tuscon", "Albuquerque", "Santa Fe", "Flagstaff", "Phoenix", "Las Vegas",
         "Reno", "Idaho Falls", "Seattle", "Olympia", "Tacoma", "Eugene", "Salem", "Eureka", "San Francisco", "Oakland",
         "Sacramento", "Los Angeles", "San Diego", "Anaheim", "Pasadena", "San Jose", "Fresno", "Juneau", "Anchorage",
         "Honolulu", "Hilo", "Charleston", "Toledo", "Fort Wayne", "Carson City"]]
}
letters = [chr(no) for no in range(97, 123)]
hangings = [" ┌─────┐\n ┃     \n ┃       \n ┃       \n/-\\", " ┌─────┐\n ┃    O\n ┃       \n ┃       \n/-\\",
            " ┌─────┐\n ┃    O\n ┃    |  \n ┃       \n/-\\", " ┌─────┐\n ┃    O\n ┃   /|  \n ┃       \n/-\\",
            " ┌─────┐\n ┃    O\n ┃   /|\\\n ┃       \n/-\\", " ┌─────┐\n ┃    O\n ┃   /|\\\n ┃   /   \n/-\\",
            " ┌─────┐\n ┃    O\n ┃   /|\\\n ┃   / \\\n/-\\"]
numbers = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve",
           "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "twenty-one",
           "twenty-two", "twenty-three", "twenty-four", "twenty-five"]
verb = ["is" if n == 1 else "are" for n in range(26)]
suffix = ["" if n == 1 else "'s" for n in range(26)]
