from pokemon.mons import *
from random import choice, sample


class TreeMon:
    def __init__(self, abils, *sets):
        self.abils = abils
        self.sets = sets

    def unpack(self):
        s = choice(self.sets)
        return {"level": 50, "ability": choice(self.abils), "item": s[0], "moves": s[1]}


trees = {
    "Venusaur": TreeMon(("Overgrow", "Chlorophyll"),
                        ("Big Root", ["Leech Seed", "Toxic", "Synthesis", "Ingrain"]),
                        ("Grassium Z", ["Roar", "Venoshock", "Power Whip", "Earthquake"]),
                        ("Salac Berry", ["Energy Ball", "Sludge Bomb", "Grass Knot", "Protect"]),
                        ("Venusaurite", ["Synthesis", "Substitute", "Sludge Bomb", "Giga Drain"])),
    "Charizard": TreeMon(("Blaze", "Solar Power"),
                         ("Salac Berry", ["Dragon Claw", "Fire Fang", "Belly Drum", "Shadow Claw"]),
                         ("Charti Berry", ["Dragon Claw", "Shadow Claw", "Rock Slide", "Dragon Dance"]),
                         ("Charizardite X", ["Dragon Rush", "Flare Blitz", "Dragon Dance", "Rock Slide"]),
                         ("Charizardite Y", ["Heat Wave", "Solar Beam", "Air Slash", "Focus Blast"])),
    "Blastoise": TreeMon(("Torrent", "Rain Dish"),
                         ("Zoom Lens", ["Aqua Ring", "Rock Slide", "Aqua Tail", "Iron Defense"]),
                         ("Blastoisinite", ["Water Pulse", "Aura Sphere", "Dark Pulse", "Dragon Pulse"]),
                         ("Leftovers", ["Fake Out", "Earthquake", "Aqua Tail", "Rock Slide"]),
                         ("Custap Berry", ["Yawn", "Hydro Pump", "Blizzard", "Dark Pulse"])),
    "Beedrill": TreeMon(("Swarm", "Sniper"),
                        ("Expert Belt", ["Poison Jab", "Pursuit", "Fell Stinger", "Toxic"]),
                        ("Occa Berry", ["Infestation", "Protect", "Attract", "Toxic"]),
                        ("Beedrillite", ["Poison Jab", "U-turn", "Brick Break", "X-Scissor"]),
                        ("Beedrillite", ["Poison Jab", "Pin Missile", "Brick Break", "Protect"])),
    "Pidgeot": TreeMon(("Keen Eye", "Tangled Feet"),
                       ("Charti Berry", ["Aerial Ace", "Steel Wing", "Thief", "Roost"]),
                       ("Flyinium Z", ["Mirror Move", "Twister", "Sand Attack", "Double Team"]),
                       ("Pidgeotite", ["Hurricane", "Hyper Beam", "Tailwind", "Quick Attack"]),
                       ("Pidgeotite", ["Hurricane", "Feather Dance", "Roost", "Hyper Beam"])),
    "Raichu": TreeMon(("Static", "Lightning Rod"),
                      ("Shuca Berry", ["Nuzzle", "Focus Blast", "Sweet Kiss", "Charge Beam"]),
                      ("Air Balloon", ["Fake Out", "Volt Tackle", "Reversal", "Light Screen"])),
    "Raichu Alolan": TreeMon(("Static", "Lightning Rod"),
                             ("Twisted Spoon", ["Volt Switch", "Safeguard", "Psyshock", "Disarming Voice"]),
                             ("Focus Sash", ["Thunderbolt", "Psychic", "Grass Knot", "Nasty Plot"])),
    "Sandslash": TreeMon(("Sand Veil", "Sand Rush"),
                         ("Quick Claw", ["Dig", "Poison Jab", "Swagger", "Sand Attack"]),
                         ("Smooth Rock", ["Sandstorm", "Earthquake", "Stone Edge", "X-Scissor"])),
    "Sandslash Alolan": TreeMon(("Snow Cloak", "Slush Rush"),
                         ("Focus Sash", ["Counter", "Defense Curl", "Ice Ball", "Gyro Ball"]),
                         ("Icium Z", ["Hail", "Icicle Spear", "Iron Head", "Aurora Veil"])),
    "Nidoqueen": TreeMon(("Poison Point", "Rivalry"),
                         ("Payapa Berry", ["Chip Away", "Swagger", "Helping Hand", "Flatter"]),
                         ("Absorb Bulb", ["Thunderbolt", "Hyper Beam", "Earth Power", "Counter"]),
                         ("Black Sludge", ["Sludge Bomb", "Earth Power", "Flamethrower", "Ice Beam"]),
                         ("Black Sludge", ["Poison Jab", "Dragon Tail", "Bulldoze", "Earthquake"])),
    "Nidoking": TreeMon(("Poison Point", "Rivalry"),
                        ("King's Rock", ["Bulldoze", "Megahorn", "Rock Slide", "Sucker Punch"]),
                        ("Black Sludge", ["Amnesia", "Sludge Bomb", "Flamethrower", "Protect"]),
                        ("Black Sludge", ["Earth Power", "Sludge Bomb", "Protect", "Fire Blast"]),
                        ("Buginium Z", ["Earthquake", "Poison Jab", "Megahorn", "Protect"])),
    "Ninetales": TreeMon(("Flash Fire", "Drought"),
                         ("Passho Berry", ["Will-O-Wisp", "Hex", "Confuse Ray", "Flame Burst"]),
                         ("Wide Lens", ["Fire Blast", "Dark Pulse", "Hypnosis", "Energy Ball"])),
    "Ninetales Alolan": TreeMon(("Snow Cloak", "Snow Warning"),
                         ("Icium Z", ["Aurora Veil", "Hypnosis", "Dream Eater", "Blizzard"]),
                         ("Psychium Z", ["Freeze-Dry", "Dazzling Gleam", "Extrasensory", "Ice Shard"])),
    "Dugtrio": TreeMon(("Sand Veil", "Arena Trap"),
                       ("Passho Berry", ["Sand Attack", "Pursuit", "Tri Attack", "Dig"]),
                       ("Bright Powder", ["Fissure", "Toxic", "Substitute", "Sandstorm"])),
    "Dugtrio Alolan": TreeMon(("Sand Veil", "Tangling Hair"),
                              ("Expert Belt", ["Dig", "Rock Slide", "Iron Head", "Sandstorm"]),
                              ("Choice Band", ["Earthquake", "Night Slash", "Iron Head", "Stone Edge"])),
    "Arcanine": TreeMon(("Intimidate", "Flash Fire"),
                        ("Firium Z", ["Flamethrower", "Solar Beam", "Burn Up", "Sunny Day"]),
                        ("Weakness Policy", ["Extreme Speed", "Crunch", "Overheat", "Roar"]),
                        ("White Herb", ["Overheat", "Sunny Day", "Solar Beam", "Extreme Speed"]),
                        ("Fightinium Z", ["Close Combat", "Flare Blitz", "Crunch", "Extreme Speed"])),
    "Alakazam": TreeMon(("Synchronize", "Inner Focus"),
                        ("Twisted Spoon", ["Energy Ball", "Psychic", "Telekinesis", "Guard Split"]),
                        ("Focus Sash", ["Psych Up", "Encore", "Protect", "Psychic"]),
                        ("Alakazite", ["Psychic", "Focus Blast", "Shadow Ball", "Grass Knot"]),
                        ("Choice Specs", ["Psychic", "Focus Blast", "Dazzling Gleam", "Trick"])),
    "Machamp": TreeMon(("Guts", "No Guard"),
                       ("Rawst Berry", ["Dynamic Punch", "Payback", "Foresight", "Wide Guard"]),
                       ("Expert Belt", ["Ice Punch", "Cross Chop", "Fire Punch", "Focus Energy"]),
                       ("Choice Scarf", ["Dynamic Punch", "Ice Punch", "Rock Slide", "Earthquake"]),
                       ("Flame Orb", ["Protect", "Earthquake", "Close Combat", "Payback"])),
    "Tentacruel": TreeMon(("Clear Body", "Liquid Ooze"),
                          ("Black Sludge", ["Ice Beam", "Sludge Wave", "Hex", "Toxic Spikes"]),
                          ("Poisonium Z", ["Rapid Spin", "Poison Jab", "Waterfall", "Swords Dance"]),
                          ("Focus Sash", ["Hydro Pump", "Sludge Bomb", "Blizzard", "Mirror Coat"]),
                          ("Black Sludge", ["Surf", "Toxic", "Venoshock", "Protect"])),
    "Golem": TreeMon(("Rock Head", "Sturdy"),
                     ("Absorb Bulb", ["Stone Edge", "Earthquake", "Sandstorm", "Autotomize"]),
                     ("Focus Sash", ["Rock Slide", "Earthquake", "Explosion", "Autotomize"])),
    "Golem Alolan": TreeMon(("Magnet Pull", "Sturdy"),
                            ("Air Balloon", ["Wild Charge", "Double-Edge", "Rock Blast", "Earthquake"]),
                            ("Weakness Policy", ["Rock Slide", "Earthquake", "Explosion", "Rock Polish"])),
    "Slowbro": TreeMon(("Oblivious", "Own Tempo"),
                       ("Sitrus Berry", ["Yawn", "Psychic", "Calm Mind", "Water Pulse"]),
                       ("Quick Claw", ["Flamethrower", "Ice Beam", "Slack Off", "Water Pulse"]),
                       ("Leftovers", ["Psychic", "Surf", "Slack Off", "Amnesia"]),
                       ("Slowbronite", ["Psychic", "Surf", "Blizzard", "Trick Room"])),
    "Muk": TreeMon(("Stench", "Sticky Hold"),
                   ("Black Sludge", ["Poison Jab", "Stockpile", "Swallow", "Mud-Slap"]),
                   ("Quick Claw", ["Gunk Shot", "Shadow Sneak", "Brick Break", "Explosion"])),
    "Muk Alolan": TreeMon(("Poison Touch", "Gluttony"),
                          ("Air Balloon", ["Minimize", "Acid Spray", "Rest", "Snarl"]),
                          ("Liechi Berry", ["Crunch", "Belch", "Shadow Sneak", "Stone Edge"])),
    "Gengar": TreeMon(("Cursed Body", ),
                      ("Focus Sash", ["Shadow Ball", "Dream Eater", "Nightmare", "Hypnosis"]),
                      ("Expert Belt", ["Sucker Punch", "Fire Punch", "Ice Punch", "Will-O-Wisp"]),
                      ("Payapa Berry", ["Shadow Ball", "Energy Ball", "Dazzling Gleam", "Round"]),
                      ("Gengarite", ["Sludge Bomb", "Thunderbolt", "Shadow Ball", "Destiny Bond"])),
    "Electrode": TreeMon(("Soundproof", "Static"),
                         ("Shuca Berry", ["Swagger", "Light Screen", "Charge Beam", "Thunder Wave"]),
                         ("Focus Sash", ["Electro Ball", "Taunt", "Protect", "Explosion"]),
                         ("Air Balloon", ["Thunderbolt", "Mirror Coat", "Thief", "Protect"]),
                         ("Damp Rock", ["Rain Dance", "Thunder", "Taunt", "Light Screen"])),
    "Exeggutor": TreeMon(("Chlorophyll", "Harvest"),
                         ("Petaya Berry", ["Psyshock", "Grass Knot", "Light Screen", "Synthesis"]),
                         ("Grassium Z", ["Leaf Storm", "Psychic", "Sludge Bomb", "Grassy Terrain"])),
    "Exeggutor Alolan": TreeMon(("Frisk", "Harvest"),
                                ("Sitrus Berry", ["Dragon Tail", "Flamethrower", "Hypnosis", "Giga Drain"]),
                                ("Assault Vest", ["Dragon Hammer", "Wood Hammer", "Earthquake", "Brick Break"])),
    "Marowak": TreeMon(("Rock Head", "Lightning Rod"),
                       ("Red Card", ["Bone Rush", "Double Kick", "Endeavor", "Smack Down"]),
                       ("Thick Club", ["Earthquake", "Stone Edge", "Brick Break", "Brutal Swing"])),
    "Marowak Alolan": TreeMon(("Cursed Body", "Lightning Rod"),
                              ("Air Balloon", ["Will-O-Wisp", "Hex", "Thunder", "Rain Dance"]),
                              ("Thick Club", ["Shadow Bone", "Flare Blitz", "Detect", "Stomping Tantrum"])),
    "Weezing": TreeMon(("Levitate", ),
                       ("Payapa Berry", ["Pain Split", "Explosion", "Haze", "Will-O-Wisp"]),
                       ("Safety Goggles", ["SLudge Bomb", "Fire Blast", "Stockpile", "Swallow"]),
                       ("Black Sludge", ["Sludge Bomb", "Thunder", "Fire Blast", "Shadow Ball"]),
                       ("Chesto Berry", ["Toxic", "Will-O-Wisp", "Stockpile", "Rest"]))
}
if __name__ == "__main__":
    testerToSeeIfMoveHasBeenAdded = movedict["hex"]


def get_treemons(n):
    a = weighted_sample(list(trees), lambda l: len(trees[l].sets), n)
    if n == 1:
        return getMon(a[0], **trees[a[0]].unpack())
    else:
        return [getMon(g, **trees[g].unpack()) for g in a]
