# A Pokewalker-esque minigame.
from pokemon.battle import *
grasslands = "Grasslands"
beach = "Beach"
plains = "Plains"
bay = "Bay"
ocean = "Ocean"
city = "City"
savanna = "Savanna"
desert = "Desert"
lake = "Lake"
mire = "Mire"
forest = "Forest"
taiga = "Taiga"
foothills = "Foothills"
volcano = "Volcano"
mountains = "Mountains"
snowpeaks = "Snowpeaks"
snowfields = "Snowfields"
mapColors = {
    grasslands: "40ca65", beach: "ffe97f", plains: "88d10e", bay: "76aef2", ocean: "3d3dc2", city: "808080",
    savanna: "cbcf0e", desert: "f8d10e", lake: "0098eb", mire: "747f0e", forest: "007f0e", taiga: "007f55",
    foothills: "d8844b", volcano: "c22700", mountains: "ad5114", snowpeaks: "e5e5e5", snowfields: "93e5e5"
}
lowerMaps = {g.lower(): g for g in mapColors}

mapMons = {
    "Bulbasaur": {grasslands: 1, forest: 0.5},
    "Charmander": {volcano: 1, mountains: 0.5},
    "Squirtle": {beach: 1, lake: 0.5},
    "Caterpie": {forest: 10, mire: 5, plains: 10, grasslands: 10, savanna: 5},
    "Metapod": {forest: 5, mire: 2.5, plains: 5, grasslands: 5, savanna: 2.5},
    "Weedle": {forest: 5, mire: 10, plains: 10, grasslands: 10, savanna: 5},
    "Kakuna": {forest: 2.5, mire: 5, plains: 5, grasslands: 5, savanna: 2.5},
    "Pidgey": {forest: 8, grasslands: 10, plains: 10},
    "Pidgeotto": {forest: 4, grasslands: 5, plains: 5},
    "Rattata": {city: 10, plains: 5, grasslands: 5, savanna: 2},
    "Raticate": {city: 4, plains: 2, grasslands: 2, savanna: 0.2},
    "Spearow": {grasslands: 7, plains: 7},
    "Fearow": {grasslands: 2, plains: 2},
    "Ekans": {grasslands: 5, plains: 5, city: 2},
    "Arbok": {grasslands: 1, plains: 1},
    "Pikachu": {forest: 3, city: 1, taiga: 2},
    "Sandshrew": {desert: 5, savanna: 3, foothills: 3},
    "Sandslash": {desert: 2, savanna: 1, foothills: 0.5},
    "NidoranF": {plains: 5, savanna: 2, foothills: 1},
    "Nidorina": {plains: 2, savanna: 1, foothills: 0.5},
    "NidoranM": {plains: 5, savanna: 2, foothills: 1},
    "Nidorino": {plains: 2, savanna: 1, foothills: 0.5},
    "Clefairy": {mountains: 2},
    "Vulpix": {volcano: 4, foothills: 2, desert: 3},
    "Ninetales": {volcano: 1},
    "Jigglypuff": {foothills: 2},
    "Zubat": {mountains: 8, forest: 2},
    "Golbat": {mountains: 2},
    "Oddish": {grasslands: 4, forest: 3},
    "Gloom": {grasslands: 1, forest: 1},
    "Vileplume": {forest: 0.5},
    "Paras": {mire: 6, forest: 2},
    "Parasect": {mire: 1},
    "Venonat": {mire: 8, forest: 3},
    "Venomoth": {mire: 2},
    "Diglett": {mountains: 2, foothills: 4, desert: 2, beach: 4},
    "Dugtrio": {mountains: 1, foothills: 2, desert: 1, beach: 2},
    "Meowth": {city: 4, grasslands: 2},
    "Persian": {city: 1},
    "Psyduck": {lake: 5, beach: 2, bay: 1},
    "Golduck": {lake: 1},
    "Mankey": {forest: 1, foothills: 1, mountains: 1},
    "Primeape": {foothills: 0.2, mountains: 0.2},
    "Growlithe": {volcano: 4, foothills: 2, desert: 3},
    "Arcanine": {volcano: 0.5},
    "Poliwag": {lake: 5},
    "Poliwhirl": {lake: 1},
    "Abra": {forest: 2},
    "Machop": {foothills: 4, mountains: 5},
    "Machoke": {foothills: 1, mountains: 2},
    "Bellsprout": {grasslands: 3, forest: 2},
    "Weepinbell": {grasslands: 0.5, forest: 0.5},
    "Tentacool": {bay: 10, ocean: 10},
    "Tentacruel": {bay: 3, ocean: 3},
    "Geodude": {mountains: 5, volcano: 5, snowpeaks: 2},
    "Graveler": {mountains: 1, volcano: 1},
    "Ponyta": {plains: 1},
    "Slowpoke": {mire: 2, lake: 3, beach: 3},
    "Magnemite": {city: 1},
    "Farfetch'd": {plains: 2, savanna: 2},
    "Doduo": {foothills: 2, savanna: 2},
    "Seel": {bay: 1, snowfields: 4},
    "Dewgong": {snowfields: 1},
    "Grimer": {city: 5, mire: 2},
    "Muk": {city: 3},
    "Shellder": {bay: 2, snowfields: 2},
    "Gastly": {forest: 2, taiga: 2, snowpeaks: 1},
    "Haunter": {forest: 0.5, taiga: 0.5},
    "Onyx": {mountains: 2},
    "Drowzee": {plains: 2},
    "Krabby": {beach: 10, bay: 2},
    "Kingler": {beach: 2},
    "Voltorb": {city: 2},
    "Exeggcute": {plains: 2, forest: 2},
    "Cubone": {savanna: 3, desert: 2, foothills: 4},
    "Hitmonlee": {mountains: 1},
    "Hitmonchan": {mountains: 1},
    "Lickitung": {foothills: 1},
    "Koffing": {city: 5, mire: 2},
    "Weezing": {city: 1.5},
    "Rhyhorn": {mountains: 2, foothills: 1},
    "Chansey": {grasslands: 2},
    "Tangela": {forest: 2, mire: 3},
    "Kangaskhan": {foothills: 2, savanna: 1, desert: 1},
    "Horsea": {bay: 4, ocean: 5},
    "Seadra": {ocean: 1},
    "Goldeen": {lake: 5, bay: 3},
    "Seaking": {lake: 0.5, bay: 1},
    "Staryu": {beach: 1},
    "Mr. Mime": {plains: 2},
    "Scyther": {grasslands: 2, plains: 2, mire: 2, forest: 2},
    "Jynx": {snowfields: 1, snowpeaks: 2},
    "Electabuzz": {city: 1, grasslands: 1},
    "Magmar": {volcano: 3},
    "Pinsir": {grasslands: 1},
    "Tauros": {plains: 2, savanna: 1},
    "Magikarp": {lake: 10, bay: 10, ocean: 5},
    "Gyarados": {lake: 0.2, bay: 0.2},
    "Lapras": {ocean: 0.5},
    "Ditto": {plains: 1},
    "Eevee": {plains: 1, grasslands: 1, forest: 1},
    "Vaporeon": {beach: 1, lake: 1},
    "Jolteon": {city: 1, forest: 1},
    "Flareon": {volcano: 1, foothills: 1},
    "Snorlax": {grasslands: 1},
    "Dratini": {lake: 0.3, mountains: 1},

    # GEN II

    "Chikorita": {grasslands: 1, plains: 0.5},
    "Cyndaquil": {volcano: 1, foothills: 0.5},
    "Totodile": {mire: 1, lake: 0.5},
    "Sentret": {grasslands: 5, plains: 5, savanna: 5},
    "Furret": {grasslands: 2, plains: 2, savanna: 2},
    "Hoothoot": {forest: 4, taiga: 4},
    "Noctowl": {forest: 1, taiga: 1},
    "Ledyba": {forest: 4, mire: 4},
    "Ledian": {mire: 1},
    "Spinarak": {forest: 5, mire: 7},
    "Ariados": {mire: 1},
    "Chinchou": {bay: 4, ocean: 5},
    "Lanturn": {bay: 1, ocean: 2},
    "Natu": {forest: 2, taiga: 3},
    "Mareep": {plains: 4},
    "Marill": {lake: 3, beach: 2},
    "Sudowoodo": {forest: 2},
    "Hoppip": {grasslands: 7, plains: 4},
    "Skiploom": {grasslands: 3, plains: 2},
    "Jumpluff": {grasslands: 1},
    "Aipom": {forest: 2},
    "Sunkern": {grasslands: 4},
    "Sunflora": {grasslands: 3},
    "Yanma": {plains: 5, grasslands: 5, savanna: 5},
    "Wooper": {mire: 3},
    "Quagmire": {mire: 1},
    "Espeon": {savanna: 1, plains: 1},
    "Umbreon": {city: 1, forest: 1},
    "Murkrow": {city: 3, forest: 2},
    "Misdreavus": {taiga: 4},
    "Unown": {desert: 2},
    "Wobbuffet": {mountains: 1},
    "Girafarig": {grasslands: 1, plains: 1},
    "Pineco": {forest: 2, taiga: 5}
}

dayGens = [[2, 4], [4, 3], [3, 6], [6, 1], [1, 7], [7, 5], [5, 2]]
